name: 'Setup Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform-versions:
    name: 'Terraform Versions'
    runs-on: ubuntu-latest
    steps:
    - uses: https://github.com/actions/checkout@v3
    - uses: https://github.com/hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color